name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: |
          cd quote_of_the_day
          cargo build --verbose

      - name: Run tests
        run: |
          cd quote_of_the_day
          cargo test --verbose

      - name: Celebrate Success 🎉
        if: success()
        run: |
          echo "🎊 All checks passed! Here's a random fun fact:"
          curl -s https://uselessfacts.jsph.pl/random.txt?language=en | grep -v '^source:'
